version: '2'

services:
  
  clamav-app:
    image: tiredofit/clamav
    container_name: clamav-app
    volumes:
    - ./data/clamav:/data
    - ./logs/clamav:/var/log/clamav
    environment:
    - ZABBIX_HOSTNAME=clamav-app
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

